language: cpp

compiler:
    - gcc
    - clang

before_install:
    - echo $LANG
    - echo $LC_ALL
    - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update -qq && echo "linux platform"; fi
    - if [ $TRAVIS_OS_NAME == osx ]; then brew update && echo "osx platform"; fi

before_script:
    - mkdir build
    - cd build
    - cmake ..
    - make help

script: 
    - make -j2
    - make test

os:
    - linux
    - osx