version: 1.0.{build}

branches:
  only:
  - master

configuration: Release

platform:
- x64
- Win32

clone_folder: c:\projects\zealous-octo-b

init:
- env

before_build:
- cd c:\projects\zealous-octo-b
- mkdir build
- cd build
- cmake --help
- if "%PLATFORM%"=="Win32" cmake -G"Visual Studio 11 2012" ..
- if "%PLATFORM%"=="x64" cmake -G"Visual Studio 11 2012 Win64" ..
- cd ..

build:
  project: build\HELLO.sln
  parallel: true
  verbosity: normal

test_script:
- cd build
- ctest -v --build-config Release

on_finish:
- ps: '# $blockRdp = $true; iex ((new-object net.webclient).DownloadString(''https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1''))'