version: 1.0.{build}

branches:
  except:
  - gh-pages

configuration: Release

os:
- Windows Server 2012 R2
- MinGW

platform:
- x64
- Win32

clone_folder: c:\projects\zealous-octo-b

init:
- env

before_build:
- cd c:\projects\zealous-octo-b
- mkdir build
- cd build
- cmake --help
- if "%PLATFORM%"=="Win32" cmake -G"Visual Studio 11 2012" ..
- if "%PLATFORM%"=="x64" cmake -G"Visual Studio 11 2012 Win64" ..
- if "%OS_THING%"=="MinGW" cmake -G"MinGW Makefiles" ..

build_script:
- cmake --build . --config %CONFIGURATION%

test_script:
- ctest -v --build-config %CONFIGURATION%

on_finish:
- ps: '# $blockRdp = $true; iex ((new-object net.webclient).DownloadString(''https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1''))'
