version: 1.0.{build}

branches:
  except:
  - gh-pages

configuration: 
- Release
- RelWithDebInfo
- Debug

clone_folder: c:\projects\zealous-octo-b

init:
- env
- set PATH=C:\MinGW\bin;%PATH%

environment:
  matrix:
  - GENERATOR: Visual Studio 11 2012 Win64
  - GENERATOR: Visual Studio 11 2012
  - GENERATOR: MinGW Makefiles

install:
- if "%GENERATOR%"=="MinGW Makefiles" del "%ProgramFiles(x86)%\Git\bin\sh.exe"
- c:\projects\zealous-octo-b\appveyor\install_dependencies.bat
- ps: $oldPath=(Get-ItemProperty -Path 'Registry::HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Session Manager\Environment' -Name PATH).Path
- ps: $newPath=$oldPath+";C:\$ENV:POCO_INSTALL_PREFIX\bin"
- ps: Write-Host $newPath
- ps: Set-ItemProperty -Path 'Registry::HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Session Manager\Environment' -Name PATH –Value $newPath

before_build:
- cd c:\projects\zealous-octo-b
- mkdir build
- cd build
- cmake --help
- cmake -G"%GENERATOR%" .. -DPoco_DIR="%POCO_INSTALL_PREFIX%\lib\cmake\Poco"

build_script:
- cmake --build . --config %CONFIGURATION%

test_script:
- echo %PATH%
- ctest -v --build-config %CONFIGURATION%

on_finish:
- ps: '# $blockRdp = $true; iex ((new-object net.webclient).DownloadString(''https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1''))'
