version: 1.0.{build}-{branch}

branches:
  except:
  - gh-pages

configuration: 
- Release
- RelWithDebInfo
- Debug

clone_folder: c:\projects\zealous-octo-b

init:
- env
- set POCO_INSTALL_PREFIX=%PROGRAMFILES%\Poco
- set PATH=C:\MinGW\bin;%PATH%;%POCO_INSTALL_PREFIX%\bin

environment:
  matrix:
  - GENERATOR: Visual Studio 11 2012 Win64
  - GENERATOR: Visual Studio 11 2012
  - GENERATOR: MinGW Makefiles

install:
- %APPVEYOR_BUILD_FOLDER%\appveyor\setMinGW.bat
- %APPVEYOR_BUILD_FOLDER%\appveyor\install_dependencies.bat

before_build:
- cd %APPVEYOR_BUILD_FOLDER%
- mkdir build
- cd build
- cmake --help
- cmake -G"%GENERATOR%" .. -DPoco_DIR="%POCO_INSTALL_PREFIX%\lib\cmake\Poco"

build_script:
- cmake --build . --config %CONFIGURATION%

test_script:
- echo %PATH%
- ctest -v --build-config %CONFIGURATION%

on_finish:
- ps: '# $blockRdp = $true; iex ((new-object net.webclient).DownloadString(''https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1''))'
